version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npm test